### PR TITLE
docs: Added stickiness to examples and README

### PR DESCRIPTION
**Pull request by mervin-hemaraju-cko**
- Added stickiness in complete-nlb example
- Documented stickiness in README.md

### CODE REVIEW

**Comment by antonbabenko** [comment]
Looks good. Please fix the docs to make GH checks green.

**Comment by mervin-hemaraju-cko** [comment]
> Looks good. Please fix the docs to make GH checks green.

New commit pushed to fix the formatting

**Review by antonbabenko — CHANGES_REQUESTED** [review]
There is no need to do changes inside wrappers folder because it is auto generated using pre-commit-terraform hook. The rest looks good.

**Comment by mervin-hemaraju-cko** [comment]
> There is no need to do changes inside wrappers folder because it is auto generated using pre-commit-terraform hook. The rest looks good.

-Restored the wrapper and updated README

**Review by antonbabenko — CHANGES_REQUESTED** [review]
Only change code in examples folder. The rest is not needed for this small PR.

**Pull request closed without merging**
