### PR TITLE
Adding CI to module

### PR DESCRIPTION
**Pull request by brandoconnor**
## Added
* TravisCI configuration added and now passing.
* badge added to docs. (will alter this to use TravisCI under terraform-aws-modules once reviewed)
* permissions section now in the example readme.
* placeholder shell script added for CI deployment. Eventually this should conditionally release to the registry when those APIs become available.

## Changed
* altered tf variable `aws_region` to `region`.
* replaced hardcoding the region to instead use a random region as retrieved by an awscli docker container within CI.
* example cert is now a regionally-specific resource enabling tests to run in various regions at once and not collide.
* ruby version bump means `Rhcl` becomes `rhcl`.

### CODE REVIEW

**Comment by brandoconnor** [comment]
Resolves https://github.com/terraform-aws-modules/terraform-aws-alb/issues/3 once merged.

**Comment by brandoconnor** [comment]
This is the build of the PR: https://travis-ci.org/run-at-scale/terraform-aws-alb/builds/290279127

I suppose in this PR state, it's probably worth setting up Travis for this project. Doing that shortly.

**Comment by brandoconnor** [comment]
Thanks for the travis permissions @antonbabenko but it looks like one more step is needed: making me admin of the repo so I can both do the registry publish and enable the TravisCI build.

I get the following within TraivsCI and can't enable due to perms:
screen shot 2017-10-24 at 12 59 05 am

I see the following in the terraform registry:
screen shot 2017-10-24 at 12 43 56 am

Unfortunately it looks like kitchen terraform doesn't fully support version 0.10.x just yet so I'm getting some spotty results. I'm going to disable nightly builds when this is up to avoid the flip flop of status due to incompatibility.

**Comment by antonbabenko** [comment]
Done.

**Comment by brandoconnor** [comment]
Hmm since the incoming branch is from a forked repo I can't run the build until this is merged. Doing that now.

**Pull request merged**
