### PR TITLE
fix: Update CI configuration files to use latest version

### PR DESCRIPTION
**Pull request by bryantbiggs**
## Description

- Update GitHub action versions to use latest. This remove warnings related to https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- Ensure pre-commit config is aligned with latest
- Add `lock.yml` workflow to automatically lock issues and PRs after 30 days. Theres a lot "Me too" or "I have this issue, when will this get fixed" on really old/stale issues and in order to properly triage, users need to supply their configurations. This workflow is pulled from the AWS provider's repo to force users to fill out a proper issue ticket and keep chatter out of merged PRs or old issues

## Motivation and Context

- Patch warnings on CI checks to keep output clean
- Focus on new issues and PRs

## Breaking Changes

- No

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by antonbabenko** [comment]
@bryantbiggs I am blind here... Where does the requirement for 0.13.1 is coming from (in [this failed step](https://github.com/terraform-aws-modules/terraform-aws-alb/actions/runs/3345583303/jobs/5541298720#step:5:72))? Is there a bug in one of the action?

**Comment by bryantbiggs** [comment]
I know what the issue is - but I am horrible at Javascript/Typescript and I haven't had time to dig in and try to finally solve it. You can see https://github.com/clowdhaus/terraform-min-max/pull/12 - the current functionality is recursively traversing down from the directory specified and grabbing ALL of the versions and then taking the first one in the array. This is why the wrapper's version is getting picked up when it shouldn't even be under consideration when trying to determine the version. I need to update the logic to NOT recursively traverse down all sub-directories and only look at the current directory's files for the version. Once the action is updated to fix that scenario, all of these remaining PRs will be resolved (using the new version of the action that is)

Know any Javascript/Typescript devs?! It should be easy (I think) 😅

**Comment by antonbabenko** [comment]
I see... I've been successfully avoiding Javascript during my entire career... I will ask tomorrow if anyone can help with this.

**Comment by bryantbiggs** [comment]
Awesome! I'll update the linked PR to ensure the checks reflect the expected outcomes. That will better shape up whether the proposed changes meet the needs or not more clearly

**Comment by bryantbiggs** [comment]
wooohoooo!!! thanks a ton @jotasixto

**Comment by jotasixto** [comment]
> wooohoooo!!! thanks a ton @jotasixto

@bryantbiggs @antonbabenko Thank you all for your great work in this community.

**Review by antonbabenko — APPROVED** [review]
Hige thanks @jotasixto !

**Comment by antonbabenko** [comment]
This PR is included in version 8.2.1 :tada:

**Pull request merged**
