### PR TITLE
fix: Explicitly setting http_tcp_listener.action_type to forward fails

### PR DESCRIPTION
**Pull request by Jarodiv**
## Description
Make the `http_tcp_listener` accept `"forward"` as explicitly set value.

## Motivation and Context
If you need to set the value of `action_type` explicitly (e.g. to make redirecting optional), there is no working way to do so.
This solves https://github.com/terraform-aws-modules/terraform-aws-alb/issues/280

## Breaking Changes
There should be no negative effect on backwards compatibility with the current major version.

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by Jarodiv** [comment]
'Keep alive' comment

**Comment by manjitkumar** [comment]
It looks like this is going to help. Thanks @Jarodiv for 
Can we please get this one rolling? @antonbabenko @brandonjbjelland @angstwad

**Review by antonbabenko — APPROVED** [review]

**Comment by antonbabenko** [comment]
@Jarodiv Thank you very much for this improvement!

**Comment by antonbabenko** [comment]
This PR is included in version 8.6.1 :tada:

**Pull request merged**
