### PR TITLE
feat: Add support for XFF/TLS headers

### PR DESCRIPTION
**Pull request by Jarodiv**
## Description
hashicorp/terraform-provider-aws/pull/29792

## Motivation and Context
hashicorp/terraform-provider-aws/pull/29792
Solves #283

## Breaking Changes
none

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by antonbabenko** [comment]
This PR is included in version 8.6.0 :tada:

**Comment by Prasad1826** [comment]
`enable_xff_client_port` default to true is a breaking change for apps that rely on `x-forwarded-for` as its not including port by default

**Comment by antonbabenko** [comment]
@falc410 `enable_xff_client_port` has `true` by default in the Terraform AWS provider, so you will have to specify the changes in your IaC configuration or pin version of this module to accept only patches (not minor releases, like this one was).

**Comment by falc410** [comment]
@antonbabenko Thanks for the reply. That is interesting to know, because according to the AWS documentation it should default to false, see https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_LoadBalancerAttribute.html 

> routing.http.xff_client_port.enabled - Indicates whether the X-Forwarded-For header should preserve the source port that the client used to connect to the load balancer. The possible values are true and false. The default is false

**Comment by nunofernandes** [comment]
@falc410 , that's the AWS API.. On the terraform-aws-provider it's set to true. See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb:

> enable_xff_client_port - (Optional) Indicates whether the X-Forwarded-For header should preserve the source port that the client used to connect to the load balancer in application load balancers. Defaults to true.

**Comment by bryantbiggs** [comment]
@falc410 raise an issue on the AWS provider - they could add this to v5 to have it set to `false` by default. In general, the provider should match the underlying API and its default settings (unless there are strong reasons to deviate)

**Comment by Jarodiv** [comment]
To add my two cents, as the contributor of that change:

@antonbabenko already pointed it out, I indeed did follow the Terraform implementation. I'm aware that they changed the default but since this module basically is a wrapper for the Terraform resources, I decided that it should behave the same way in the interest of transparency.

**Pull request merged**
