### PR TITLE
Intro possibility to redirect HTTP port to HTTPS

### PR DESCRIPTION
**Pull request by sysC0D**
# PR o'clock

## Description

Adding optional option to redirect HTTP port to HTTPS with "redirect" action on ALB resource.

### Checklist

* [x] `terraform fmt` and `terraform validate` both work from the root and `examples/alb_test_fixture` directories (look in CI for an example)
* [x] Tests for the changes have been added and passing (for bug fixes/features)
* [x] Test results are pasted in this PR (in lieu of CI)
* [x] Docs have been added/updated (for bug fixes/features)
* [x] Any breaking changes are noted in the description above

### CODE REVIEW

**Comment by neoshadybeat** [comment]
Is there any updated?

**Comment by okonon** [comment]
@sysC0D can you please to see if you can fix that conflict?

**Comment by okonon** [comment]
@brandoconnor  is it possible to merge this PR or #78?

**Comment by luckytaxi** [comment]
ANy update? Two PRs that failed due to invalid aws creds. Anyone can push this through?

**Comment by MihaiAnei** [comment]
> ANy update? Two PRs that failed due to invalid aws creds. Anyone can push this through?

I would also very much like being able to redirect HTTP to HTTPS from ALB, even if is this MR or https://github.com/terraform-aws-modules/terraform-aws-alb/pull/78

**Comment by antonbabenko** [comment]
Hi all,

Forgot to mention that all types of ALB listener actions (redirect, fixed-response, authenticate-cognito, authenticate-oidc) are supported since [v5.3.0](https://github.com/terraform-aws-modules/terraform-aws-alb/releases/v5.3.0) of this module.

Check out code in [examples/complete-alb](https://github.com/terraform-aws-modules/terraform-aws-alb/tree/master/examples/complete-alb) for more details.

Closing this issue/pr.

**Pull request closed without merging**
